controller_manager:
  ros__parameters:
    update_rate: 200  # Hz

    amber_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    amber_position_controller:
      type: forward_command_controller/ForwardCommandController

    amber_position_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      #position_controllers/JointGroupPositionController
      #forward_command_controller/ForwardCommandController
      #joint_trajectory_controller/JointTrajectoryController
      #effort_controllers/JointGroupEffortController

amber_forward_position_controller:
  ros__parameters:
    action_ns: forward_position_controller
    default: false
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7
    interface_name: position


amber_position_trajectory_controller:
  ros__parameters:
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7

    command_interfaces:
      - position
      - velocity

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 200.0 # Defaults to 50
    action_monitor_rate: 20.0 # Defaults to 20

    allow_partial_joints_goal: false # Defaults to false
    open_loop_control: true
    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.01 # Defaults to 0.01
      goal_time: 0.0 # Defaults to 0.0 (start immediately)
