controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    amber_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

amber_arm_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
    allow_partial_joints_goal: true
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7
